.gitignore
README.md
toolchest_client/_internal_utils.py
toolchest_client/auth.py
toolchest_client/exceptions.py
toolchest_client/query.py
toolchest_client/tools.py

Adds:
- Pretty printed job status updates
- PyCharm gitignore
Modifies:
- Readme/doc ordering and imports
- Function signature for tool arguments
Also: we'll need to set guidelines for PRs soon, since this is open source now.

Doc cleanup and prettifying

---

poetry.lock
pyproject.toml

Modifies:
- Updates default Poetry reference to public PyPI

Fixes Poetry config to reference public PyPI by default.

---

toolchest_client/__init__.py
toolchest_client/query.py
toolchest_client/tools/__init__.py
toolchest_client/tools/api.py
toolchest_client/tools/test.py
toolchest_client/tools/tool.py
toolchest_client/tools/unicycler.py

Adds:
- Support for Unicycler 0.4.9
- Support for multiple named inputs

Add Unicycler and named inputs

---

docs/user/quickstart.rst
pyproject.toml

Updates quickstart guide to be in line with current infrastructure.

up-to-date docs quickfixes (v0.7.9)

---

docs/user/quickstart.rst
pyproject.toml

Docs quickfixes 

---

pyproject.toml
toolchest_client/__init__.py
toolchest_client/files/__init__.py
toolchest_client/files/general.py
toolchest_client/files/merge.py
toolchest_client/files/split.py
toolchest_client/tools/__init__.py
toolchest_client/tools/api.py
toolchest_client/tools/arg_whitelist.py
toolchest_client/tools/cellranger.py
toolchest_client/tools/tests/test_cellranger.py
toolchest_client/tools/tests/test_star.py
toolchest_client/tools/tool.py

Add Cell Ranger mkfastq

---

pyproject.toml
tests/test_tools.py
toolchest_client/api/query.py
toolchest_client/files/__init__.py
toolchest_client/files/unpack.py
toolchest_client/tools/api.py
toolchest_client/tools/kraken2.py
toolchest_client/tools/tool.py

Adds:
- Automatic output file decompression from `.tar.gz`, supporting multiple output files
- Hard linking to move directories and their contents
- Tool specific output checking

Add better Kraken 2 multiple output handling

---

pyproject.toml
toolchest_client/api/auth.py
toolchest_client/files/unpack.py
toolchest_client/tools/kraken2.py
toolchest_client/tools/tests/test_kraken2.py
toolchest_client/tools/tool.py

Modifies:
- No longer requires an empty output directory.
- A check for overwriting files was moved to a preflight check.
Still needs:
- Better docs.

Add Zoey suggested changes

---

pyproject.toml
toolchest_client/api/query.py

Modifies:
- Actually download files

Fix file downloading

---

toolchest_client/tools/star.py

Modifies:
- The STAR per-file limit

Increase the per-file limit for STAR

---

tests/test_shi7.py

Marks shi7 tests as ready to run and updates output directory variables.

feat: update shi7 integration tests

---

tests/test_shi7.py
toolchest_client/tools/shi7.py

Simplifies the test directories for shi7 integration tests.

fix: change shi7 test directories

---

toolchest_client/tools/alphafold.py
toolchest_client/tools/api.py

- Enables all AlphaFold whitelisted parameters (reduced db and prokaryote list implemented now)
- Refactors code to match other tool's arg processing.
- Updates doc string

feat: add full alphafold functionality

---

toolchest_client/api/query.py

Moves the error throwing for failed run execution from the api into the synchronous flow for execution to allow for async runs to call `get_status` without throwing an error on failed runs.

fix: no longer throw error when checking failed status asynchronously

---

.circleci/config.yml

Increases # of CircleCI parallel runs from 2 to 10.

chore: increase # of CircleCI parallel runs

---

tests/test_diamond.py
toolchest_client/__init__.py
toolchest_client/tools/__init__.py
toolchest_client/tools/api.py
toolchest_client/tools/diamond.py
toolchest_client/tools/tool_args.py

Adds the blastx mode for diamond. The test will be updated after the backend is merged.

feat: add diamond blastx tool

---

toolchest_client/tools/tool.py

* Refactors the `_wait_for_threads_to_upload` loop to avoid `while True` syntax.

refactor: upload loop

---

tests/test_chaining.py
tests/test_shi7.py

Changes shi7/shogun test assertion checks to be in line with #202.

fix: shi7/shogun test assertions

---

.circleci/config.yml
tests/test_humann3.py
toolchest_client/tools/api.py
toolchest_client/tools/humann.py
toolchest_client/tools/tool_args.py

Adds support for the following utilities:
- humann_barplot
- humann_gene_families_genus_level
- humann_join_tables
- humann_reduce_table
- humann_regroup_table
- humann_renorm_table
- humann_split_stratified_table
- humann_unpack_pathways

feat: support for humann3 utilities

---

tests/test_salmon.py
toolchest_client/__init__.py
toolchest_client/tools/__init__.py
toolchest_client/tools/api.py
toolchest_client/tools/salmon.py
toolchest_client/tools/tool_args.py

Added:
- Salmon
- Docs for Salmon: https://docs.trytoolchest.com/docs/salmon

feat: add salmon

---

poetry.lock
pyproject.toml

Updates the min python version to 3.7 and docker to 6.0.0. Also ran a poetry update to update other dependencies in the lock and fix the `pywitn32` issue.

feat: update min python version and dependencies

---

poetry.lock
pyproject.toml
tests/test_python3.py
tests/util/streaming_script.py
toolchest_client/api/query.py
toolchest_client/api/streaming.py
toolchest_client/tools/api.py
toolchest_client/tools/tool.py

This fixes failures for integration tests where streaming is disabled.

fix: un-revert streaming, check for streaming_client in query.py

---

pyproject.toml
toolchest_client/tools/lug.py

chore: increase Lug file limit to 4TB (#296)

---

pyproject.toml
toolchest_client/api/query.py
toolchest_client/api/streaming.py
toolchest_client/tools/api.py
toolchest_client/tools/tool.py

Disables output streaming for Jupyter notebooks, and adds Lug fixes

Fix output streaming conflict with Jupyter notebooks; Lug fixes

---

toolchest_client/api/query.py

Fixes the issues from the ticket. Docker in progress still could be improved but should give some indication and updates to a final "uploaded" message.

feat: improve run output
