docs/index.rst
docs/user/quickstart.rst

Updates `/docs` files to be consistent with edits made to docstrings in PR #2

Make /docs consistent with docstring edits

---

.circleci/config.yml
pyproject.toml

Adds a basic CircleCI config. We'll also want to add lint and tests to CircleCI later.
Adds:
- Automatic deployment of builds to PyPI. `staging` deploys to TestPyPI (tested), and `main` deploys to normal PyPI (untested).

Add basic CircleCI config

---

poetry.lock
pyproject.toml
toolchest_client/__init__.py
toolchest_client/query.py
toolchest_client/tools.py
toolchest_client/version.py

Adds a `test` pipeline segment.
Adds:
- `test` pipeline segment to allow demonstrating/trying out the interface without a specific tool to distract.
- `.env` handling with `python-dotenv`

Add test pipeline segment

---

toolchest_client/tools/api.py

Changes:
* moved `tool_args` to the front of the declared arguments for every tool function argument (for consistency + ease of usability when porting to R)

Change tool argument order

---

toolchest_client/__init__.py

Adds:
- Support for consistent buffer flushing. This allows consistent output when loaded in R via `reticulate`

Override built-in print statement to flush after every print

---

toolchest_client/__init__.py
toolchest_client/exceptions.py
toolchest_client/query.py
toolchest_client/status.py

This is facilitated by raising a `ToolchestJobError` if a `NOT OK` status is detected during any status update/check (e.g., while waiting for the job to finish executing, while waiting for downloads, etc.).
This effectively punts the task of distinguishing errors and marking failed jobs to the master/worker node levels. (This is okay because this simplifies the task at hand.)

Add detection of errors in master/worker nodes to client

---

toolchest_client/tools/api.py
toolchest_client/tools/kraken2.py

Adds database selection for `kraken2`. Defaults to `standard` (the standard Kraken2 DB) for backwards compatibility.

Add updated Kraken2 options

---

toolchest_client/query.py

Changes outputted time elapsed during execution to `(h:mm:ss`) instead of `(#s)`.

Add improved time display

---

pyproject.toml
toolchest_client/tools/tool.py

Adds:
- Explicit concept of jobs in Tools to distinguish between Tools which have multiple input files and parallel runs which have multiple split input files.
Fixes support for Unicycler (non-parallel) in v0.7.x.

Fix support for Unicycler

---

pyproject.toml
toolchest_client/api/auth.py
toolchest_client/api/exceptions.py
toolchest_client/api/query.py
toolchest_client/tools/tool.py

Adds `_validate_key()` to `auth.py` and moves the key validation check from `Query.run_query()` to `Tool.run()`, where it occurs before any jobs are spawned.
Note that any invalid key checks can take as long as a minute. The key validity is determined to be invalid by the API, which hangs and eventually times out upon encountering an invalid key. We'll need to make a change to the API to speed this up as well.

Key validation restructuring

---

pyproject.toml
toolchest_client/files/general.py
toolchest_client/tools/tool.py

Adds a check on the size of an input provided as an S3 URI, as a safeguard. The limit is the same as the size of a user-uploaded file (4.5 GB).
Note: This limit will be removed once multipart uploads are implemented for client-uploaded inputs (so that the behavior of the limts for S3 URI inputs matches), though we may want to increase the size of the limit rather than remove it altogether.

Limit on S3 URI input size

---

pyproject.toml

Modifies:
- `boto3` install, so that it's a normal dependency rather than a dev dependency

Fix boto3 install

---

pyproject.toml
toolchest_client/api/query.py
toolchest_client/files/general.py
toolchest_client/files/s3.py
toolchest_client/tools/tool.py

Modifies:
- Refactors propagation of S3 tags for inputs in `tools/tool.py` and `api/query.py`.
- Enforces uniform naming scheme of variables/methods (`inputs_are_in_s3()`, `input_is_in_s3`).
`inputs_are_in_s3` used to be a variable storing whether each input file path is an S3 URI. The propagation of this information has been changed to a method in `files/s3.py`, and all checks of a single input file path are simply calls to `input_file_path.startswith(S3_PREFIX)`.
The old structure of `_generate_jobs()` in `tools/tool.py` has been restored, yielding file path strings instead of (file path, file_is_in_s3) tuples.

Refactor `inputs_are_in_s3`

---

toolchest_client/api/query.py

Adds:
- Support for multipart uploads via boto3
- Shifts download to boto3 as well
Removes:
- Usage of pre-signed URLs and raw file posting via `requests`

Add support for multipart uploads

---

pyproject.toml
toolchest_client/tools/test.py

Modifies:
- Test tool per-file limit from 4.5 GB (default) to 256 GB

Increase test tool limit to 256 GB

---

toolchest_client/tools/shi7.py
toolchest_client/tools/star.py
toolchest_client/tools/test.py
toolchest_client/tools/tool.py

Modifies:
- What values is used to limit per-tool upload sizes

Use per-tool limit rather than single part upload limit to check file sizes

---

pyproject.toml
tests/test_star.py

Modifies:
- Version number
- Range for parallel STAR integration test to manage the leeway given to a smaller non-parallel integration test

Cleanup for v0.7.37

---

toolchest_client/files/unpack.py

Modifies:
- Removes the expectation that there will be a `output/` component of `output.tar.gz`

[Hotfix] Shift burden of unpack structure to the worker node

---

pyproject.toml
toolchest_client/api/query.py
toolchest_client/tools/api.py
toolchest_client/tools/megahit.py
toolchest_client/tools/tool.py

Adds:
- Propagation of the order of each input within each tool prefix for `megahit`. This order is 0-indexed and will be passed to the API when uploading/registering each input file. 
For example, `read_one = ["input_one", "input_two", "input_three"]` will result in: 
```
input_prefix_mapping["input_one"]["order"]: 0
input_prefix_mapping["input_two"]["order"]: 1
input_prefix_mapping["input_three"]["order"]: 2
```
Note: the order value is stored as the `"order"` parameter within `tool_prefix_mapping`., though it is eventually passed as `tool_prefix_order` to the API.
Requires:
- https://github.com/trytoolchest/toolchest-api/pull/31
- https://github.com/trytoolchest/toolchest-worker-node/pull/30

Propagate order of inputs within tool arg prefix

---

pyproject.toml
toolchest_client/tools/megahit.py
toolchest_client/tools/shi7.py
toolchest_client/tools/tool.py

Adds:
- Capability of tools to have an unlimited number of input files, by specifying `max_inputs=None` in the class `__init__()` function. 
(Note: `max_inputs` is set to `None` by default if left unspecified during `__init__()`, but all of our current tools specify `max_inputs` explicitly.)
Removes:
- The arbitrary cap of 10 input files for `megahit`.
- The arbitrary cap of 10 input files for `shi7`. 
(Both tools can now have an unlimited number of inputs.)

Remove limit on # of input files

---

pyproject.toml
tests/test_chaining.py
tests/test_download.py
tests/test_kraken2.py
toolchest_client/__init__.py
toolchest_client/api/auth.py
toolchest_client/api/download.py
toolchest_client/api/exceptions.py
toolchest_client/api/output.py
toolchest_client/api/query.py
toolchest_client/api/urls.py
toolchest_client/files/__init__.py
toolchest_client/files/s3.py
toolchest_client/files/tests/test_s3.py
toolchest_client/files/unpack.py
toolchest_client/tools/api.py

Adds:
* `toolchest.download(output_path, s3_uri="s3://your-s3-uri")` and `output.download(output_dir)`, user-invoked functions which can download an output after its job has completed.
* `ToolchestDownloadException`, a new exception thrown whenever an error is encountered in downloading or unpacking.
* Integration tests for manual downloads.
Modifies:
* Code for downloading has now been moved from `Query` to `api/downloads.py`, which serves as a single source for all download functionality.
* Downloads during `Query.run_query()` now call the functions in `api/downloads.py`.
* URLs used for the API have been moved to `api/urls.py`, which serves as a single source for all API URLs.
* All `toolchest.tool()` calls now correctly return an `Output`.
Removes:
* `presigned_s3_url` parameter for …

Refactor downloads, add download interface

---

pyproject.toml
tests/test_megahit.py
toolchest_client/api/output.py
toolchest_client/api/query.py
toolchest_client/tools/api.py

Adds:
- Two integration tests for `megahit`:
- One uses two interleaved inputs, one pair of paired-end inputs, and two single-end inputs. This matches the integration test used in the actual `megahit` package.
- The other uses two different-sized pairs of paired-end inputs, to test that the API properly processes pairs.
Both integration tests run in 2-4 minutes.
Modifies:
- Bugfix for failing integration tests not using the manual download.
- Bugfix for `megahit` inputs that are given as strings instead of lists of strings.

Megahit integration tests + integration test bugfix

---

pyproject.toml
tests/test_star.py
toolchest_client/tools/star.py

Comments out pysam requirement temporarily and also forces STAR to not be parallelized since that depends on pysam.

fix: remove pysam and STAR parallelization for now

---

tests/test_chaining.py
tests/test_download.py
tests/test_kraken2.py
tests/test_megahit.py

Redirects integration test file downloads to the private bucket, in preparation for deprecating the public bucket.

fix: get integration test files from private S3 bucket

---

toolchest_client/api/download.py
toolchest_client/api/query.py
toolchest_client/api/urls.py

Modifies:
*  In `api/query.py`, renames `_add_input_file()` to `_register_input_file()`.
* Deprecates including `is_s3` in `_register_input_file()`, which is unnecessary with `s3_uri`.
* Renames the confusing variable `PIPELINE_URL` to `PIPELINE_SEGMENT_INSTANCES_URL`.
* Removes stray comments in `_register_input_file()`.
Note: This can be merged into #94 directly. We should let integration tests run if merging to staging instead, but I'd hold off on updating to `0.8.1` until #94 is merged.

chore: refactor `PIPELINE_URL` and `_add_input_file()`

---

pyproject.toml
toolchest_client/api/query.py
toolchest_client/files/unpack.py
toolchest_client/tools/kraken2.py
toolchest_client/tools/tool.py

Allows the output path of a tool to be an s3 bucket that the worker nodes have permission to access.  Also adds s3 output type to kraken2 which will skip output compression.

feat: add support for outputting to an s3 bucket

---

toolchest_client/files/s3.py

Adds handling in `path_is_s3_uri` for a `None` value for `path`. Fixes test `test_kraken2_output_manual_download`.

fix: add support for a None-valued output_path

---

pyproject.toml
tests/test_kraken2.py
toolchest_client/api/query.py
toolchest_client/tools/api.py
toolchest_client/tools/kraken2.py
toolchest_client/tools/tests/test_kraken2.py
toolchest_client/tools/tool.py

Adds:
- Support for custom databases, specified by the `custom_database_path` argument for `toolchest.kraken2()`. (Custom DBs are only enabled for `kraken2`.)
- A custom database path must be given as an AWS S3 URI that must be accessible from Toolchest.
- Integration test for custom databases.
Modifies:
- The `test_kraken2_s3` integration test no longer unnecessarily downloads the input to local storage.

feat: custom S3 database support

---

pyproject.toml
toolchest_client/api/download.py
toolchest_client/api/query.py
toolchest_client/api/urls.py

Updates the add input file response with a file id and then calls a new api endpoint to set the file size in the DB after uploading the file to s3.

feat: add function to call api file size endpoint after s3 upload

---

pyproject.toml
tests/test_cellranger.py
tests/test_download.py
toolchest_client/api/download.py
toolchest_client/tools/cellranger.py
toolchest_client/tools/tool.py

Adds:
- Output path directory creation if `output_path` does not exist, both in tool runs and manual download.
Modifies:
- `_validate_args` in the `Tool` class no longer checks existence of the output directory.
- Integration tests (where applicable) no longer create an output dir before running a tool or downloading.
- `_is_local_path` is renamed to `_output_path_is_local`

feat: create folders along given output path

---

toolchest_client/__init__.py

Sets the version number to a default instead of erroring if the client is run from source (i.e., without the `toolchest-client` package being installed via pip).
Open question: the version number defaults to `0.0.0`, which can be confusing -- are there any other labels that might be better (e.g., `dev` or just the empty string)?

fix: set default version number

---

tests/test_download.py
toolchest_client/tools/tool.py

Modifies:
- path checking for `test_kraken2_output_manual_download` 
- output validation for parallelization tests

fix: abspath + parallel output check for tests

---

pyproject.toml
tests/test_star.py

Pysam has caused multiple issues as a package and STAR parallelization is not currently used so this pr fully removes pysam as a dependency. Either a different library or custom sam file merging code is planned to be implemented later so parallelization framework is remaining in the code for now.

fix: remove pysam due to multiple issues

---

toolchest_client/tools/tool.py

Fixes the issue where appending a `/` on the output path caused the run to fail if the directory didn't already exist. Also allows for multiple directories to be created so a user can set the output path to `{existing-directory}/new/folder/for/output` and all the sub directories will be created.

fix: remove writable dir check before creation

---

toolchest_client/tools/tool.py

Adds a check for failed threads (with a custom "run failed" printed message) at the end of a run, in order to skip the "Toolchest run complete" message if a job fails.

fix: add check for interrupted/failed threads

---

toolchest_client/tools/tool.py

Adds:
* support for async runs during failure check
* return value for failure check
* bugfix for getting `thread_output` from `self.thread_outputs`

fix: add support for async runs for failure check

---

tests/test_http.py
toolchest_client/api/query.py
toolchest_client/files/__init__.py
toolchest_client/files/general.py
toolchest_client/files/http.py

Adds support for inputs that are given as publicly accessible HTTP or HTTPS URLs.
URLs are supplied in `inputs` just like a path to a local file to upload, and are handled similarly to AWS S3 URI inputs.

feat: support for public HTTP inputs

---

toolchest_client/files/http.py

Catches the error that occurs when passing S3 URIs into `requests.head()`. Fixes integration tests for #126.

fix: S3 schema in HEAD request

---

tests/test_chaining.py
tests/test_shogun.py
toolchest_client/files/http.py
toolchest_client/tools/shogun.py

Reconfigures `shogun_align` to use `bowtie2` as its aligner (and catches an uncaught error for HTTP checks).
Note: `shogun_filter` still uses BURST since there's no easy way to configure the aligner for `shogun_filter` from the command line.

fix: reconfigure shogun_align with bowtie2

---

tests/test_star.py

Modifies:
* Integration test assertion values for STAR outputs.
Adds:
* Hash test of STAR output with non-deterministic metadata lines filtered out. (These lines contain the command used, which incorporates the Toolchest run ID.)

fix: test values for dockerized STAR

---

tests/test_async.py
tests/test_chaining.py
tests/test_clustalo.py
tests/test_diamond.py
tests/test_download.py
tests/test_filepath.py
tests/test_http.py
tests/test_kraken2.py
tests/test_megahit.py
tests/test_star.py
toolchest_client/api/download.py
toolchest_client/files/general.py
toolchest_client/tools/tool.py

Adds:
- Support for paths that contain `~`.
- Integration tests (using kraken2) for `~` filepaths.
- Absolutizing output paths (for consistency).
Modifies:
- Integration test pathing (to be compatible with absolutized output paths).

fix: absolutize output paths, support for ~ paths

---

.circleci/config.yml
tests/test_star.py

Modifies:
* Pathing for dangerous arg STAR test, in line with paths from #144.
* CircleCI config:
* Increases number of parallel testing runs from 2 to 4
* Adds printed test duration to CircleCI stdout

fix: STAR test pathing, testing config changes

---

tests/test_bowtie2.py

Now the test uses a human reads file and aligns `89.53%` of the reads instead of `0.01%`.

fix: bowtie2 integration test input file

---

tests/conftest.py
toolchest_client/__init__.py
toolchest_client/api/auth.py
toolchest_client/api/download.py
toolchest_client/api/query.py
toolchest_client/api/urls.py
toolchest_client/files/s3.py

Adds:
* Support for custom API URLs, via `toolchest.get_api_url()` and `toolchest.set_api_url()`. Custom API URLs can be set through the `TOOLCHEST_API_URL` environment variable.
Modifies:
* URL handling throughout the package. Instead of global variables stored in `api/urls.py`, every URL is now retrieved through an encapsulated function.

feat: custom API URL support

---

README.md
toolchest_client/api/output.py

Removes typo in `run_id` instantiation in `output.py`.

fix: remove run id comma

---

toolchest_client/__init__.py
toolchest_client/tools/__init__.py
toolchest_client/tools/api.py

Cleans typos in docstrings and alphabetizes tools in `api.py`.

chore: clean api.py docstrings

---

toolchest_client/tools/tool.py

Generically fixes issue with Unicycler optional inputs causing an error due to `None` being passed to os path functions during execution prep.

fix: filter none inputs

---

toolchest_client/tools/tool.py

Previous code was converting string inputs to a list of characters and breaking those runs.

fix: only run filter if inputs is already a list

---

pyproject.toml
toolchest_client/__init__.py

Disabling sentry until we added a method to limit sentry scope.

fix: temporarily disable sentry event capture

---

.circleci/config.yml
tests/test_clustalo.py
tests/test_diamond.py
tests/test_rapsearch2.py
toolchest_client/api/download.py
toolchest_client/api/output.py
toolchest_client/api/query.py
toolchest_client/files/__init__.py
toolchest_client/files/unpack.py
toolchest_client/tools/alphafold.py
toolchest_client/tools/api.py
toolchest_client/tools/bowtie2.py
toolchest_client/tools/cellranger.py
toolchest_client/tools/clustalo.py
toolchest_client/tools/demucs.py
toolchest_client/tools/diamond.py
toolchest_client/tools/kraken2.py
toolchest_client/tools/megahit.py
toolchest_client/tools/rapsearch2.py
toolchest_client/tools/shi7.py
toolchest_client/tools/shogun.py
toolchest_client/tools/star.py
toolchest_client/tools/test.py
toolchest_client/tools/tests/test_generic.py
toolchest_client/tools/tests/test_kraken2.py
toolchest_client/tools/tests/test_star.py
toolchest_client/tools/tool.py
toolchest_client/tools/unicycler.py

* Refactors `output_path` to refer _only_ to a directory. If a tool needs a file name specified as well, it should be passed into the `output_primary_name` parameter.
* Removes redundant output variables (`output_name`) and all logic related to whether `output_path` is a directory.
* Adds the `output_path` parameter in `Output.download()`. This should be used in place of the `output_dir` parameter, though the `output_dir` parameter is still supported for backwards compatibility.
This is a **breaking change**. The function calls for the following tools are affected:
* `clustalo`
* `diamond_blastp`
* `diamond_blastx`
* `rapsearch2`
For these tools, `output_path` formerly referred to an output **file**. The base file name should now be parsed into `output_primary_name` instead, and …

fix: standardize output path

---

toolchest_client/api/query.py

Retries the status check in `api/query.py` when waiting for a job to complete, up to a retry limit (currently hardcoded to 5 for each new `Query`).

feat: retry on status check timeout

---

.gitignore
toolchest_client/files/s3.py
toolchest_client/tools/tool.py

* Refactors the tracking printed statements into a pythonic `print` call with string formatting.
* Fixes status update logic in uploading. (This was causing the terminal output to stall at the "uploading" stage.)
* Adds integration test dirs to `.gitignore`.

fix: upload/download tracker bugfixes

---

tests/test_shogun.py
toolchest_client/api/status.py
toolchest_client/files/s3.py
toolchest_client/tools/tool.py

* Adds `INITIALIZING` as a `ThreadStatus`. 
* Sets all query threads to `INITIALIZING` before starting them, so that the `uploading` check in `_wait_for_threads_to_finish` correctly detects when all threads are done uploading. 
* Cleans pretty print status code line.
(This was the cause of the upload tracker display bug.)

fix: upload tracker status check

---

tests/test_kraken2.py

Separates the `test_kraken2_s3` dir from the `test_kraken2_standard` dir.

chore: kraken s3 test dir

---

toolchest_client/__init__.py

Increases Sentry's max error message length from 512 to 8192, via monkey patch.

fix: sentry max message length

---

toolchest_client/api/query.py
toolchest_client/tools/tool.py

* Handles errors that occur during uploading (i.e. before a query's `ThreadStatus` changes to `UPLOADED`). This fixes the infinite hanging bug.
* Avoids erroring if the requested tool does not specify a database.

fix: handle pipeline segments with no DB

---

.gitignore
tests/test_async.py
tests/test_bowtie2.py
tests/test_cellranger.py
tests/test_chaining.py
tests/test_clustalo.py
tests/test_database_update.py
tests/test_diamond.py
tests/test_download.py
tests/test_filepath.py
tests/test_http.py
tests/test_kraken2.py
tests/test_megahit.py
tests/test_rapsearch2.py
tests/test_shi7.py
tests/test_shogun.py
tests/test_star.py
tests/test_unicycler.py

Prefixes all integration tests with `temp_` and adds `temp_test_*` to the gitignore.

refactor: integration test dir names

---

toolchest_client/tools/tool.py

Updates the expected "success" status in `_check_thread_health()` to support async runs.

fix: async success in _check_thread_health

---

tests/test_python3.py
toolchest_client/__init__.py
toolchest_client/tools/__init__.py
toolchest_client/tools/api.py
toolchest_client/tools/python3.py
toolchest_client/tools/tool.py
toolchest_client/tools/tool_args.py

Implements a tool to run python3 scripts via Toolchest. Script must use the expected local input and output directories but are otherwise not limited.

feat: add python3 tool implementation

---

pyproject.toml
tests/test_database_update.py
toolchest_client/tools/diamond.py

Add and update database functions instantiate tools directly so any non-standard args without defaults at the tool level break those functions for that tool. This happened with the new `distributed` arg for diamond blastx so this pr adds the same default as the `api.py` function to the tool itself.

fix: add default distributed value at tool level to fix add database

---

pyproject.toml
tests/test_blastn.py
toolchest_client/tools/tool_args.py

Not sure why this worked locally but adding the dash and an integration test for the task arg.

fix: add dash in front of task arg

---

tests/test_public_uri.py
toolchest_client/api/query.py
toolchest_client/files/public_uris.py

S3 URLs don't allow head requests to get content-size prior to download

fix: skip head request for presigned s3 urls

---

tests/test_bowtie2.py
tests/test_database_update.py
tests/test_star.py
tests/util/filter_output.py

Fixes `bowtie2`-based tests by testing actual output values instead of a filesize check. 
New tests filter out non-deterministic metadata lines from the output SAM file and then hash the rest of the content, which is deterministic.

fix: bowtie2 tests

---

pyproject.toml
tests/test_python3.py
toolchest_client/api/instance_type.py
toolchest_client/api/query.py
toolchest_client/tools/api.py
toolchest_client/tools/tool.py

Adds `instance_type` and `volume_size` args to tool to allow users more flexibility in their runs. The args are top level args for python3 as the workloads for python3 are much more variable. The args are accessible via `**kwargs` for all other tools except AlphaFold, Demucs, and Transfer, which do not allow changing instance type.

feat: add capability for a user to request what instance type to run on

---

tests/test_fastqc.py
tests/util/filter_output.py

Removes the date from FastQC html output via regex as that is the only non-deterministic part of the html.

fix: filter date out of fastqc output for hashing

---

toolchest_client/api/instance_type.py

Adds:
- GPU instance type (matching internal GPU instance type)
Manually tested previously with Lug, but opting not to add an integration test for GPU instances. Open to adding a test.

feat: add GPU instance type (TC-28)

---

.circleci/config.yml
pytest.ini
tests/test_database_update.py
toolchest_client/tools/api.py
toolchest_client/tools/tool.py

* Adds an integration test for a custom database update with an S3 prefix as input and an auto-generated `database_primary_name`.
* Modifies function call for `add_database_update` to mandate `database_primary_name`.
* Removes `database_primary_name` sanitization.
* Increases CI parallelism to 8.

feat: S3 prefix input handling for custom DB updates

---

toolchest_client/api/query.py

Fixes bug where S3 URI prefixes with trailing slashes were not properly registered when used as input.

fix: strip trailing slashes from S3 URIs in input register (TC-20)

---

toolchest_client/api/query.py
toolchest_client/tools/tool.py

Adds a progress bar that looks like:
```
Pushing [=>                                                 ]  166.2MB/5.831GB 
```
Instead of giving the standard Docker-style updates on multiple lines, this just overwrites the most recent line to give rough progress.

feat: add docker upload progress log (TC-60)

---

tests/test_python3.py

Should not fix the issue itself but provides more clarity.

fix: use different directory for docker test

---

toolchest_client/tools/api.py

Exposes `volume_size` as a user settable top level param and defaults to tool independent increased size. Also changes the instance type to match to not be over-provisioned.

feat: update volume size and instance type for db change functions

---

tests/test_cellranger.py

- Re-enables cellranger tests for CI.
- Refactors local cellranger test to download individual files, instead of downloading and unzipping a tarball of files.
- Refactors S3 cellranger test to use an S3 prefix (containing uncompressed files) instead of a S3-stored `.tar.gz` archive of the "directory" of files.
Note: `.tar.gz` inputs for cellranger can no longer be passed via S3 URLs.

chore: re-enable cellranger tests (TCP-105)

---

pyproject.toml
tests/test_python3.py
toolchest_client/api/query.py

This pr assumes if an image isn't found locally that it's a public image on dockerhub. A local image is still used if a matching one is found even if a public dockerhub image of the same name and tag exists. If no local or public image exists it will fail during execution instead of during the pre-execution client steps.

feat: add support for public images in dockerhub

---

toolchest_client/api/query.py

Fixes bug where the server could start and the server-side stream could time out before `_upload_docker_image` completed (e.g., when pushing a large docker image from the client).

fix: move TRANSFERRED_FROM_CLIENT status update

---

pyproject.toml
toolchest_client/tools/api.py

Leaves `tool_args` the same as that would require a worker node pr and isn't exposed publicly.

feat: switch docker_tag to version_tag

---

docs/docs/tool-reference/taxonomic-classifiers/centrifuge.md
docs/mkdocs.yaml
toolchest_client/tools/tool_args.py

Fixes typos/formatting in the `centrifuge` docs page, and adds an unsupported argument to the `centrifuge` blacklist.

chore: fix centrifuge docs bullets, blacklist

---

docs/docs/getting-started/using-files.md
toolchest_client/tools/tool.py

May be worth renaming `compress_inputs` to `retain_directories` or similar in the future. It's only really used for that now.

feat: retain directory structure for compressed inputs
